// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// PayClient is the client API for Pay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PayClient interface {
	PayMoney(ctx context.Context, in *PayMoneyRequest, opts ...grpc.CallOption) (*PayMoneyReply, error)
	RefundMoney(ctx context.Context, in *RefundMoneyRequest, opts ...grpc.CallOption) (*RefundMoneyReply, error)
}

type payClient struct {
	cc grpc.ClientConnInterface
}

func NewPayClient(cc grpc.ClientConnInterface) PayClient {
	return &payClient{cc}
}

func (c *payClient) PayMoney(ctx context.Context, in *PayMoneyRequest, opts ...grpc.CallOption) (*PayMoneyReply, error) {
	out := new(PayMoneyReply)
	err := c.cc.Invoke(ctx, "/service.Pay/PayMoney", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payClient) RefundMoney(ctx context.Context, in *RefundMoneyRequest, opts ...grpc.CallOption) (*RefundMoneyReply, error) {
	out := new(RefundMoneyReply)
	err := c.cc.Invoke(ctx, "/service.Pay/RefundMoney", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayServer is the server API for Pay service.
// All implementations must embed UnimplementedPayServer
// for forward compatibility
type PayServer interface {
	PayMoney(context.Context, *PayMoneyRequest) (*PayMoneyReply, error)
	RefundMoney(context.Context, *RefundMoneyRequest) (*RefundMoneyReply, error)
	mustEmbedUnimplementedPayServer()
}

// UnimplementedPayServer must be embedded to have forward compatible implementations.
type UnimplementedPayServer struct {
}

func (UnimplementedPayServer) PayMoney(context.Context, *PayMoneyRequest) (*PayMoneyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayMoney not implemented")
}
func (UnimplementedPayServer) RefundMoney(context.Context, *RefundMoneyRequest) (*RefundMoneyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefundMoney not implemented")
}
func (UnimplementedPayServer) mustEmbedUnimplementedPayServer() {}

// UnsafePayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PayServer will
// result in compilation errors.
type UnsafePayServer interface {
	mustEmbedUnimplementedPayServer()
}

func RegisterPayServer(s grpc.ServiceRegistrar, srv PayServer) {
	s.RegisterService(&_Pay_serviceDesc, srv)
}

func _Pay_PayMoney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayMoneyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServer).PayMoney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Pay/PayMoney",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServer).PayMoney(ctx, req.(*PayMoneyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pay_RefundMoney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundMoneyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServer).RefundMoney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Pay/RefundMoney",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServer).RefundMoney(ctx, req.(*RefundMoneyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pay_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Pay",
	HandlerType: (*PayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PayMoney",
			Handler:    _Pay_PayMoney_Handler,
		},
		{
			MethodName: "RefundMoney",
			Handler:    _Pay_RefundMoney_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message/pay.proto",
}
