// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: message/ticket.proto

package service

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BookTicketsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderID     uint64   `protobuf:"varint,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	ScheduleID  uint64   `protobuf:"varint,2,opt,name=ScheduleID,proto3" json:"ScheduleID,omitempty"`
	SeatType    uint64   `protobuf:"varint,3,opt,name=SeatType,proto3" json:"SeatType,omitempty"`
	PassengerID []uint64 `protobuf:"varint,4,rep,packed,name=PassengerID,proto3" json:"PassengerID,omitempty"`
}

func (x *BookTicketsRequest) Reset() {
	*x = BookTicketsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_ticket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookTicketsRequest) ProtoMessage() {}

func (x *BookTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_ticket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookTicketsRequest.ProtoReflect.Descriptor instead.
func (*BookTicketsRequest) Descriptor() ([]byte, []int) {
	return file_message_ticket_proto_rawDescGZIP(), []int{0}
}

func (x *BookTicketsRequest) GetOrderID() uint64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

func (x *BookTicketsRequest) GetScheduleID() uint64 {
	if x != nil {
		return x.ScheduleID
	}
	return 0
}

func (x *BookTicketsRequest) GetSeatType() uint64 {
	if x != nil {
		return x.SeatType
	}
	return 0
}

func (x *BookTicketsRequest) GetPassengerID() []uint64 {
	if x != nil {
		return x.PassengerID
	}
	return nil
}

type BookTicketsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *BookTicketsReply) Reset() {
	*x = BookTicketsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_ticket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookTicketsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookTicketsReply) ProtoMessage() {}

func (x *BookTicketsReply) ProtoReflect() protoreflect.Message {
	mi := &file_message_ticket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookTicketsReply.ProtoReflect.Descriptor instead.
func (*BookTicketsReply) Descriptor() ([]byte, []int) {
	return file_message_ticket_proto_rawDescGZIP(), []int{1}
}

func (x *BookTicketsReply) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type RefundTicketsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderID uint64 `protobuf:"varint,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
}

func (x *RefundTicketsRequest) Reset() {
	*x = RefundTicketsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_ticket_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundTicketsRequest) ProtoMessage() {}

func (x *RefundTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_ticket_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundTicketsRequest.ProtoReflect.Descriptor instead.
func (*RefundTicketsRequest) Descriptor() ([]byte, []int) {
	return file_message_ticket_proto_rawDescGZIP(), []int{2}
}

func (x *RefundTicketsRequest) GetOrderID() uint64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

type RefundTicketsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *RefundTicketsReply) Reset() {
	*x = RefundTicketsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_ticket_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundTicketsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundTicketsReply) ProtoMessage() {}

func (x *RefundTicketsReply) ProtoReflect() protoreflect.Message {
	mi := &file_message_ticket_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundTicketsReply.ProtoReflect.Descriptor instead.
func (*RefundTicketsReply) Descriptor() ([]byte, []int) {
	return file_message_ticket_proto_rawDescGZIP(), []int{3}
}

func (x *RefundTicketsReply) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_message_ticket_proto protoreflect.FileDescriptor

var file_message_ticket_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22,
	0x8c, 0x01, 0x0a, 0x12, 0x42, 0x6f, 0x6f, 0x6b, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x53, 0x65, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x50, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x49, 0x44, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x04, 0x52, 0x0b, 0x50, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x49, 0x44, 0x22, 0x2a,
	0x0a, 0x10, 0x42, 0x6f, 0x6f, 0x6b, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x30, 0x0a, 0x14, 0x52, 0x65,
	0x66, 0x75, 0x6e, 0x64, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x22, 0x2c, 0x0a, 0x12,
	0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xa0, 0x01, 0x0a, 0x06, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x47, 0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x12, 0x1b, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42,
	0x6f, 0x6f, 0x6b, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4d,
	0x0a, 0x0d, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x12,
	0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x2d, 0x5a,
	0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x6d, 0x61,
	0x63, 0x68, 0x65, 0x6e, 0x67, 0x63, 0x68, 0x65, 0x6e, 0x67, 0x2f, 0x31, 0x32, 0x33, 0x30, 0x36,
	0x2f, 0x61, 0x70, 0x70, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_ticket_proto_rawDescOnce sync.Once
	file_message_ticket_proto_rawDescData = file_message_ticket_proto_rawDesc
)

func file_message_ticket_proto_rawDescGZIP() []byte {
	file_message_ticket_proto_rawDescOnce.Do(func() {
		file_message_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_ticket_proto_rawDescData)
	})
	return file_message_ticket_proto_rawDescData
}

var file_message_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_message_ticket_proto_goTypes = []interface{}{
	(*BookTicketsRequest)(nil),   // 0: service.BookTicketsRequest
	(*BookTicketsReply)(nil),     // 1: service.BookTicketsReply
	(*RefundTicketsRequest)(nil), // 2: service.RefundTicketsRequest
	(*RefundTicketsReply)(nil),   // 3: service.RefundTicketsReply
}
var file_message_ticket_proto_depIdxs = []int32{
	0, // 0: service.Ticket.BookTickets:input_type -> service.BookTicketsRequest
	2, // 1: service.Ticket.RefundTickets:input_type -> service.RefundTicketsRequest
	1, // 2: service.Ticket.BookTickets:output_type -> service.BookTicketsReply
	3, // 3: service.Ticket.RefundTickets:output_type -> service.RefundTicketsReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_ticket_proto_init() }
func file_message_ticket_proto_init() {
	if File_message_ticket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_ticket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookTicketsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_ticket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookTicketsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_ticket_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefundTicketsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_ticket_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefundTicketsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_ticket_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_ticket_proto_goTypes,
		DependencyIndexes: file_message_ticket_proto_depIdxs,
		MessageInfos:      file_message_ticket_proto_msgTypes,
	}.Build()
	File_message_ticket_proto = out.File
	file_message_ticket_proto_rawDesc = nil
	file_message_ticket_proto_goTypes = nil
	file_message_ticket_proto_depIdxs = nil
}
