// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// TicketClient is the client API for Ticket service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TicketClient interface {
	BookTickets(ctx context.Context, in *BookTicketsRequest, opts ...grpc.CallOption) (*BookTicketsReply, error)
	RefundTickets(ctx context.Context, in *RefundTicketsRequest, opts ...grpc.CallOption) (*RefundTicketsReply, error)
}

type ticketClient struct {
	cc grpc.ClientConnInterface
}

func NewTicketClient(cc grpc.ClientConnInterface) TicketClient {
	return &ticketClient{cc}
}

func (c *ticketClient) BookTickets(ctx context.Context, in *BookTicketsRequest, opts ...grpc.CallOption) (*BookTicketsReply, error) {
	out := new(BookTicketsReply)
	err := c.cc.Invoke(ctx, "/service.Ticket/BookTickets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) RefundTickets(ctx context.Context, in *RefundTicketsRequest, opts ...grpc.CallOption) (*RefundTicketsReply, error) {
	out := new(RefundTicketsReply)
	err := c.cc.Invoke(ctx, "/service.Ticket/RefundTickets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketServer is the server API for Ticket service.
// All implementations must embed UnimplementedTicketServer
// for forward compatibility
type TicketServer interface {
	BookTickets(context.Context, *BookTicketsRequest) (*BookTicketsReply, error)
	RefundTickets(context.Context, *RefundTicketsRequest) (*RefundTicketsReply, error)
	mustEmbedUnimplementedTicketServer()
}

// UnimplementedTicketServer must be embedded to have forward compatible implementations.
type UnimplementedTicketServer struct {
}

func (UnimplementedTicketServer) BookTickets(context.Context, *BookTicketsRequest) (*BookTicketsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookTickets not implemented")
}
func (UnimplementedTicketServer) RefundTickets(context.Context, *RefundTicketsRequest) (*RefundTicketsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefundTickets not implemented")
}
func (UnimplementedTicketServer) mustEmbedUnimplementedTicketServer() {}

// UnsafeTicketServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TicketServer will
// result in compilation errors.
type UnsafeTicketServer interface {
	mustEmbedUnimplementedTicketServer()
}

func RegisterTicketServer(s grpc.ServiceRegistrar, srv TicketServer) {
	s.RegisterService(&_Ticket_serviceDesc, srv)
}

func _Ticket_BookTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).BookTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Ticket/BookTickets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).BookTickets(ctx, req.(*BookTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_RefundTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).RefundTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Ticket/RefundTickets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).RefundTickets(ctx, req.(*RefundTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ticket_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Ticket",
	HandlerType: (*TicketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BookTickets",
			Handler:    _Ticket_BookTickets_Handler,
		},
		{
			MethodName: "RefundTickets",
			Handler:    _Ticket_RefundTickets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message/ticket.proto",
}
